config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :users
  resources :rents, only: [:new, :create, :show]
  devise_for :users, :path_prefix => 'ao3'

  root to: 'home#index'
  
  devise_scope :user do
    authenticated :user do
      root to: 'vehicles#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/Vehicle.rb
class Vehicle < ApplicationRecord
  validates :manufacture, :model, presence: true
  validates :license_plate, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates :manufacture, presence: true
  validates :model, presence: true
  validates :license_plate, uniqueness: true, presence: true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :vehicle

  validates :start_date, :end_date, presence: true
  validates :cpf, presence: true, length: {is: 11}
  validate :start_date_uniq, :end_date_uniq

  scope :by_vehicle, ->(id) { where(vehicle_id: id) }
  scope :active, -> { where("end_date >= ?" , Date.current) }

  private

  def start_date_uniq
    rents = Rent.active.by_vehicle(vehicle_id)

    dates = rents.select do |rent|
      start_date.between?(rent.start_date, rent.end_date)
    end

    errors.add(:start_date, 'Already rented at this date') unless dates.blank?
  end

  def end_date_uniq
    rents = Rent.active.by_vehicle(vehicle_id)

    dates = rents.select do |rent|
      end_date.between?(rent.start_date, rent.end_date)
    end

    errors.add(:end_date, 'Already rented at this date') unless dates.blank?
  end  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: { case_sensitive: false }, presence: true
  validates :login, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def new
    @rent = Rent.new
    set_vehicle(params[:vehicle])
    @rent.vehicle = @vehicle
    respond_with(@rent)
  end

  def create
    return if incorrect_dates
    @rent = Rent.create(rent_params)
    set_vehicle(@rent.vehicle_id)
    respond_with(@rent)
  end

  def show
    @rent = Rent.find(params[:id])
    set_vehicle(@rent.vehicle_id)
    respond_with(@rent)
  end

  private

  def rent_params
    params.require(:rent).permit(%i[cpf start_date end_date vehicle_id])
  end

  def set_vehicle(vehicle_id)
    @vehicle = Vehicle.find(vehicle_id)
  end

  def incorrect_dates
    start_date = rent_params[:start_date].to_date
    end_date = rent_params[:end_date].to_date

    return if start_date < end_date && start_date >= Date.current
      
    redirect_to new_rent_path(vehicle: rent_params[:vehicle_id]), 
      alert: "Please provide valid date values."
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:name)
  end

  def show
    respond_with(@user)
  end

  def edit
    respond_with(@user)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    respond_with @user
  end

  def update
    @user.update(user_update_params)
    respond_with @user
  end

  def destroy
    @user.destroy
    respond_with @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(%i[name email login password password_confirmation])
  end

  def user_update_params
    return user_params if user_params[:password].present?
      
    user_params.permit(%i[name email login])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle, only: %i[show edit update destroy]

  respond_to :html

  def index
    @vehicles = Vehicle.all
    respond_with(@vehicles)
  end

  def show
    respond_with(@vehicle)
  end

  def new
    @vehicle = Vehicle.new
    respond_with(@vehicle)
  end

  def edit
    respond_with(@vehicle)
  end

  def create
    result =  FipeService.call(
                vehicle_params[:manufacture], 
                vehicle_params[:model], 
                vehicle_params[:model_year]
              )
    if result == 'incorret params'
      flash[:alert] = result
      redirect_to new_vehicle_path
    else
      vehicle_params[:manufacture] = result.year.model.brand.name
      vehicle_params[:model] = result.year.model.name
      vehicle_params[:model_year] = result.year.id
      @vehicle = Vehicle.create(vehicle_params)
      respond_with(@vehicle)
    end
  end

  def update
    @vehicle.update(vehicle_params)
    respond_with(@vehicle)
  end

  def destroy
    @vehicle.destroy
    respond_with(@vehicle)
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(%i[manufacture model license_plate model_year manufacture_year fuel_type color])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<div class="col-6">
  <%= simple_form_for(@car) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :model %>
      <%= f.input :manufacture %>
      <%= f.input :license_plate %>
      <%= f.input :model_year %>
      <%= f.input :manufacture_year %>
      <%= f.input :fuel_type %>
      <%= f.input :color %>
    </div>

    <div class="row mt-2">
      <div class="col-6">
        <%= link_to "Back", cars_path, class:"btn btn-secondary" %>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/index.html.erb
<h1>Cars</h1>

<div class="table-responsive col-7">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Model</th>
        <th scope="col">Manufacture</th>
        <th scope="col">License Plate</th>
        <th scope="col">Model year</th>
        <th scope="col">Manufacture year</th>
        <th scope="col">Fuel type</th>
        <th scope="col">Color</th>
        <th colspan="3" scope="col" class="text-center">actions</th>
      </tr>
    </thead>

    <tbody>
      <% @cars.each_with_index do |car, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= car.model %></td>
          <td><%= car.manufacture %></td>
          <td><%= car.license_plate %></td>
          <td><%= car.model_year %></td>
          <td><%= car.manufacture_year %></td>
          <td><%= car.fuel_type %></td>
          <td><%= car.color %></td>
          <td><%= link_to 'Show', car, class: "btn btn-info btn-sm" %></td>
          <td><%= link_to 'Edit', edit_car_path(car), class: "btn btn-warning btn-sm" %></td>
          <td><%= link_to 'Destroy', car, {
                                              method: :delete, 
                                              class: "btn btn-danger btn-sm", 
                                              data: { confirm: 'Are you sure?' }
                                            } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Car', new_car_path, class: "btn btn-lg btn-info" %>
</div>

app/views/home/index.html.erb
<h1>Reservations</h1>

<table class="responsive-table highlight">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Model</th>
      <th scope="col">Manufacture</th>
      <th scope="col">License Plate</th>
      <th scope="col">Model year</th>
      <th scope="col">Manufacture year</th>
      <th scope="col">Fuel type</th>
      <th scope="col">Color</th>
      <th colspan="1" scope="col" class="text-center">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each_with_index do |vehicle, i| %>
      <tr>
        <th scope="row"><%= i+1 %></th>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.manufacture %></td>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.model_year %></td>
        <td><%= vehicle.manufacture_year %></td>
        <td><%= vehicle.fuel_type %></td>
        <td><%= vehicle.color %></td>
        <td><%= link_to 'Rent', new_rent_path(vehicle: vehicle), class: "waves-effect waves-light btn-small" %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% if flash.present? %>
  <% flash.each do |notice, message| %>
    <script>
      var toastHTML = '<span><%= "#{notice}: #{message}" %></span>';
      M.toast({html: toastHTML})
    </script>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Vehicles', vehicles_path %></li>
      <li><%= link_to 'Users', users_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent a Car</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rents/_form.html.erb
<div class="card-panel">
  <h2><%= @vehicle.model %></h2>
  <div><b>Manufacture:</b> <%= @vehicle.manufacture %></div>
  <div><b>Plate:</b> <%= @vehicle.license_plate %></div>
  <div><b>Model year:</b> <%= @vehicle.model_year %></div>
  <div><b>Manufacture year:</b> <%= @vehicle.manufacture_year %></div>
  <div><b>Fuel:</b> <%= @vehicle.fuel_type %></div>
  <div><b>Color:</b> <%= @vehicle.color %></div>
</div>

<div class="card-panel">
  <%= simple_form_for(@rent) do |f| %>
    <%= f.input :cpf %>
    <%= f.input :start_date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :end_date, as: :string, input_html: { class: "datepicker" } %>
    <%= f.input :vehicle_id, as: :hidden, input_html: { value: @vehicle.id } %>
    <div class="row mt-2">
      <div class="col-6">
        <%= link_to "Back", root_path, class:"btn btn-secondary" %>
        <%= f.button :submit, class: "btn waves-effect waves-light" %>
      </div>
    </div>
  <% end %>
</div>

app/views/rents/new.html.erb
<h1>New Rent</h1>

<%= render 'form', rent: @rent %>

app/views/rents/show.html.erb
<div class="card-panel">
  <h2><%= @rent.vehicle.model %></h2>
  <div><b>CPF:</b> <%= @rent.cpf %></div>
  <div><b>Start Date:</b> <%= @rent.start_date %></div>
  <div><b>End Date:</b> <%= @rent.end_date %></div>
</div>

<div class="row mt-2">
  <div class="col-6">
    <%= link_to "Back", root_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="col-6">
  <%= simple_form_for @user do |f| %>
    <%= f.input :name %>
    <%= f.input :login %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <div class="row mt-2">
      <div class="col-6">
        <%= link_to "Back", users_path, class:"btn btn-secondary" %>
        <%= f.button :submit, class: "btn waves-effect waves-light" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="responsive-table highlight">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Login</th>
      <th scope="col">email</th>
      <th colspan="3" scope="col" class="text-center">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, i| %>
      <tr>
        <th scope="row"><%= i+1 %></th>
        <td><%= user.name %></td>
        <td><%= user.login %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class: "waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Destroy', user, {
                                            method: :delete, 
                                            class: "waves-effect waves-light btn-small", 
                                            data: { confirm: 'Are you sure?' }
                                          } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New User', new_user_path, class: "waves-effect waves-blue btn-large" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="card-panel">
  <h2><%= @user.name %></h2>
  <div><b>Login:</b> <%= @user.login %></div>
  <div><b>e-mail:</b> <%= @user.email %></div>
</div>

<div class="row mt-2">
  <div class="col-6">
    <%= link_to "Back", users_path, class: "btn btn-secondary" %>
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
  </div>
</div>

app/views/vehicles/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= simple_form_for(@vehicle) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div>
        <%= f.input :manufacture %>
        <%= f.input :model %>
        <%= f.input :model_year %>
        <%= f.input :manufacture_year %>
        <%= f.input :fuel_type %>
        <%= f.input :license_plate %>
        <%= f.input :color %>
      </div>

      <div class="row mt-2">
        <div class="col-6">
          <%= link_to "Back", vehicles_path, class:"waves-effect waves-light btn" %>
          <%= f.button :submit, class: "btn waves-effect waves-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<table class="responsive-table highlight">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Model</th>
      <th scope="col">Manufacture</th>
      <th scope="col">License Plate</th>
      <th scope="col">Model year</th>
      <th scope="col">Manufacture year</th>
      <th scope="col">Fuel type</th>
      <th scope="col">Color</th>
      <th colspan="3" scope="col" class="text-center">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each_with_index do |vehicle, i| %>
      <tr>
        <th scope="row"><%= i+1 %></th>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.manufacture %></td>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.model_year %></td>
        <td><%= vehicle.manufacture_year %></td>
        <td><%= vehicle.fuel_type %></td>
        <td><%= vehicle.color %></td>
        <td><%= link_to 'Show', vehicle, class: "waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle), class: "waves-effect waves-light btn-small" %></td>
        <td><%= link_to 'Destroy', vehicle, {
                                            method: :delete, 
                                            class: "waves-effect waves-light btn-small", 
                                            data: { confirm: 'Are you sure?' }
                                          } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Vehicle', new_vehicle_path, class: "waves-effect waves-light btn-large" %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/show.html.erb
<div class="card-panel">
  <h2><%= @vehicle.model %></h2>
  <div><b>Manufacture:</b> <%= @vehicle.manufacture %></div>
  <div><b>Plate:</b> <%= @vehicle.license_plate %></div>
  <div><b>Model year:</b> <%= @vehicle.model_year %></div>
  <div><b>Manufacture year:</b> <%= @vehicle.manufacture_year %></div>
  <div><b>Fuel:</b> <%= @vehicle.fuel_type %></div>
  <div><b>Color:</b> <%= @vehicle.color %></div>
</div>

<div class="row mt-2">
  <div class="col-6">
    <%= link_to "Back", vehicles_path, class: "btn btn-secondary" %>
    <%= link_to "Edit", edit_vehicle_path(@vehicle), class: "btn btn-primary" %>
  </div>
</div>